apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/xgao3/cpks-registration:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/xgao3/cpks-registration:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: cpks-registration
        chartPath: charts/cpks-registration
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/xgao3/cpks-registration'
          image.tag: '{{.DIGEST_HEX}}'
