apiVersion: v1
kind: Service
metadata:
  name: cpks-svc
  labels:
    app: cpks-svc
spec:
  ports:
    # the port that this service should serve on
    - port: 1112
  selector:
    app: cpks-app
  type: ClusterIP

