apiVersion: v1
kind: Service
metadata:
  name: vke-svc
  namespace: vke-app
  labels:
    app: vke-svc
spec:
  ports:
    # the port that this service should serve on
    - port: 1112
  selector:
    app: vke-app
  type: LoadBalancer

